"""
Markdown report renderer for ReplaySummary + EventReport list.
"""
from api.simulator.replay.harness import EventReport, ReplaySummary


def render_report(summary: ReplaySummary, reports: list[EventReport],
                  capture_id: str, top_n_outliers: int = 50) -> str:
    total = max(summary.total_events, 1)
    pct = lambda n: f"{n / total:.1%}"

    lines = [
        f"# Replay report — {capture_id}",
        "",
        "Generated by `scripts/replay_capture.py`. Plumbing-only metrics from Sprint 2a;",
        "fidelity gaps are categorized but not yet resolved (Sprint 2b material).",
        "",
        "## Summary",
        "",
        f"- Total events: {summary.total_events:,}",
        f"- Crashed: {summary.crashed:,} ({pct(summary.crashed)})",
        f"- Dispatched within ±5%: {summary.dispatched_dmg_within_5pct:,} ({pct(summary.dispatched_dmg_within_5pct)})",
        f"- Dispatched outside ±5%: {summary.dispatched_dmg_outside_5pct:,} ({pct(summary.dispatched_dmg_outside_5pct)})",
        f"- Routed to stub: {summary.stubbed:,} ({pct(summary.stubbed)})",
        f"- Missing from index: {summary.missing_from_index:,} ({pct(summary.missing_from_index)})",
        f"- No target / skipped: {summary.no_target:,} ({pct(summary.no_target)})",
        "",
        "## Per-eff_type breakdown",
        "",
        "| eff_type | dispatched | stub | missing | crashed | no_target |",
        "|---|---|---|---|---|---|",
    ]
    for eff, counts in sorted(summary.by_eff_type.items(),
                              key=lambda kv: -sum(kv[1].values())):
        lines.append(
            f"| `{eff}` | {counts.get('dispatched', 0)} | {counts.get('stub', 0)} | "
            f"{counts.get('missing', 0)} | {counts.get('crashed', 0)} | {counts.get('no_target', 0)} |"
        )
    lines.append("")

    outliers = [r for r in reports if r.delta_pct is not None]
    outliers.sort(key=lambda r: abs(r.delta_pct or 0.0), reverse=True)
    if outliers:
        lines.append(f"## Top {min(top_n_outliers, len(outliers))} outlier events (worst delta_pct first)")
        lines.append("")
        lines.append("| seq | skill_eff_id | eff_type | sim | obs | delta% |")
        lines.append("|---|---|---|---|---|---|")
        for r in outliers[:top_n_outliers]:
            lines.append(
                f"| {r.seq} | `{r.skill_eff_id}` | {r.eff_type} | {r.sim_damage} | {r.obs_damage} | {r.delta_pct * 100:+.1f}% |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"
