"""
Markdown report renderer for ReplaySummary + EventReport list.
"""
import re

from api.simulator.replay.harness import EventReport, ReplaySummary


_CARD_ID_PATTERN = re.compile(r"^c_(\d+)_")


def _extract_char_res_id(skill_eff_id: str) -> str | None:
    m = _CARD_ID_PATTERN.match(skill_eff_id)
    return m.group(1) if m else None


def render_report(summary: ReplaySummary, reports: list[EventReport],
                  capture_id: str, top_n_outliers: int = 50,
                  char_resolver=None) -> str:
    total = max(summary.total_events, 1)
    pct = lambda n: f"{n / total:.1%}"

    lines = [
        f"# Replay report — {capture_id}",
        "",
        "Generated by `scripts/replay_capture.py`. Sprint 2b enriched output:",
        "char names from deck_builder manifest where parseable.",
        "",
        "## Summary",
        "",
        f"- Total events: {summary.total_events:,}",
        f"- Crashed: {summary.crashed:,} ({pct(summary.crashed)})",
        f"- Dispatched within ±5%: {summary.dispatched_dmg_within_5pct:,} ({pct(summary.dispatched_dmg_within_5pct)})",
        f"- Dispatched outside ±5%: {summary.dispatched_dmg_outside_5pct:,} ({pct(summary.dispatched_dmg_outside_5pct)})",
        f"- Routed to stub: {summary.stubbed:,} ({pct(summary.stubbed)})",
        f"- Missing from index: {summary.missing_from_index:,} ({pct(summary.missing_from_index)})",
        f"- No target / skipped: {summary.no_target:,} ({pct(summary.no_target)})",
        "",
        "## Per-eff_type breakdown",
        "",
        "| eff_type | dispatched | stub | missing | crashed | no_target |",
        "|---|---|---|---|---|---|",
    ]
    for eff, counts in sorted(summary.by_eff_type.items(),
                              key=lambda kv: -sum(kv[1].values())):
        lines.append(
            f"| `{eff}` | {counts.get('dispatched', 0)} | {counts.get('stub', 0)} | "
            f"{counts.get('missing', 0)} | {counts.get('crashed', 0)} | {counts.get('no_target', 0)} |"
        )
    lines.append("")

    outliers = [r for r in reports if r.delta_pct is not None]
    outliers.sort(key=lambda r: abs(r.delta_pct or 0.0), reverse=True)
    if outliers:
        lines.append(f"## Top {min(top_n_outliers, len(outliers))} outlier events (worst delta_pct first)")
        lines.append("")
        lines.append("| seq | char | skill_eff_id | eff_type | sim | obs | delta% |")
        lines.append("|---|---|---|---|---|---|---|")
        for r in outliers[:top_n_outliers]:
            char_name = "?"
            char_res_id = _extract_char_res_id(r.skill_eff_id)
            if char_res_id and char_resolver is not None:
                char_name = char_resolver.name_for(char_res_id)
            lines.append(
                f"| {r.seq} | {char_name} | `{r.skill_eff_id}` | {r.eff_type} | "
                f"{r.sim_damage} | {r.obs_damage} | {r.delta_pct * 100:+.1f}% |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"
