"""
Level 3 fidelity report. Replays captured SkillEff observations against the
simulator and writes docs/research/eff_catalog_coverage.md.

Run:
  python scripts/validate_catalog_against_captures.py
"""
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CAPTURE_DIRS = [
    Path.home() / "AppData" / "Local" / "hub-czn" / "snapshots",
    REPO / "api" / "snapshots",
]
CATALOG_PATH = REPO / "api" / "data" / "eff_type_catalog.json"
COVERAGE_PATH = REPO / "docs" / "research" / "eff_catalog_coverage.md"

# Use the same regex as build_eff_catalog_scaffold.py — res_id is alphanumeric.
PATTERN = re.compile(r"SkillEff\s+\d+:[^:]+:([A-Z_][A-Z_0-9]*)")


def count_observations() -> dict:
    counts: Counter[str] = Counter()
    for d in CAPTURE_DIRS:
        if not d.exists():
            continue
        for src in d.glob("websocket_debug_*.jsonl"):
            for line in src.open(encoding="utf-8", errors="ignore"):
                for m in PATTERN.findall(line):
                    counts[m] += 1
    return dict(counts)


def main():
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    observed = count_observations()

    in_catalog = set(catalog)
    seen_types = set(observed)
    missing = seen_types - in_catalog
    unreached = in_catalog - seen_types

    dispatch_status = defaultdict(lambda: {"obs": 0, "status": "no_catalog_entry"})
    for eff, obs_count in observed.items():
        entry = dispatch_status[eff]
        entry["obs"] = obs_count
        if eff in catalog:
            ref = catalog[eff]["effect"].get("formula_ref")
            conf = catalog[eff]["confidence"]
            if ref is None:
                entry["status"] = "no_formula_ref"
            elif ref.startswith("F_UNKNOWN") or ref == "F_NOOP":
                entry["status"] = f"stub ({ref}, {conf})"
            else:
                entry["status"] = f"dispatched -> {ref} ({conf})"

    total_obs = sum(observed.values())
    dispatched_obs = sum(s["obs"] for s in dispatch_status.values() if s["status"].startswith("dispatched"))
    stub_obs = sum(s["obs"] for s in dispatch_status.values() if s["status"].startswith("stub"))
    nocat_obs = sum(s["obs"] for s in dispatch_status.values() if s["status"] == "no_catalog_entry")

    lines = [
        "# eff_type Catalog Fidelity Coverage",
        "",
        "Generated by `scripts/validate_catalog_against_captures.py`. Tracks how many",
        "captured `SkillEff` observations the simulator can dispatch through a real",
        "formula vs a stub vs nothing.",
        "",
        "## Summary",
        "",
        f"- Total observations: **{total_obs:,}**",
        f"- Dispatched to real formula: **{dispatched_obs:,}** ({dispatched_obs/max(total_obs,1):.1%})",
        f"- Routed to stub: **{stub_obs:,}** ({stub_obs/max(total_obs,1):.1%})",
        f"- No catalog entry: **{nocat_obs:,}** ({nocat_obs/max(total_obs,1):.1%})",
        f"- Catalog entries with zero observations: **{len(unreached)}**",
        "",
        "## Per-eff_type breakdown",
        "",
        "| eff_type | observed | status |",
        "|---|---|---|",
    ]
    for eff, s in sorted(dispatch_status.items(), key=lambda kv: -kv[1]["obs"]):
        lines.append(f"| `{eff}` | {s['obs']:,} | {s['status']} |")
    lines.append("")
    if missing:
        lines.append("## Observed but not in catalog")
        lines.append("")
        for eff in sorted(missing):
            lines.append(f"- `{eff}` ({observed[eff]} obs)")
    COVERAGE_PATH.parent.mkdir(parents=True, exist_ok=True)
    COVERAGE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {COVERAGE_PATH}")
    print(f"Total: {total_obs:,} / Dispatched: {dispatched_obs:,} ({dispatched_obs/max(total_obs,1):.1%})")


if __name__ == "__main__":
    main()
